In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
import pandas as pd
df=pd.read_csv('/content/gdrive/My Drive/Datasets/Titanic-Dataset.csv')

In [4]:
# Extract   'Fare' column and cmake a new DataFrame
fare = df[["Fare"]]

# Display the first 5 rows of the 'fare' DataFrame
fare.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [5]:
# Select the 'Pclass' and 'Age' columns to make a new DataFrame
class_age = df[["Pclass", "Age"]]

# Show the first 5 rows of the 'class_age' DataFrame
class_age.head()

   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

In [6]:
# make a DataFrame with the 'Survived' and 'Sex' columns
survived_gender = df[["Survived", "Sex"]]

# show the first 5 rows of the 'survived_gender' DataFrame
survived_gender.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

In [23]:
# Select passengers with a 'Fare' greater than 100 and create a new DataFrame
fare_gt_100 = df[df["Fare"] > 100]

# Print the resulting DataFrame
fare_gt_100.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,NaN
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,11.434783
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,10.313367
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C,2.526221

In [22]:
# Filter passengers in first class (Pclass = 1)
first_class = df[df["Pclass"] == 1]

# Print the result
first_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0.960417
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,0.457759
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,1.267857

In [19]:
# put passengers who are female and under 18
female_under_18 = df[(df["Age"] < 18) & (df["Sex"] == "female")]

# Print the result
female_under_18.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2.147914
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,4.175000
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,0.561014
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,0.535280
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,2.634375

In [21]:
# put passengers whose Embarked port is either 'C' or 'S'
embarked_c_or_s = df[df["Embarked"].isin(["C", "S"])]

# Print the result
embarked_c_or_s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000

In [17]:
# Filter passengers in first or second class
first_second_class = df[df["Pclass"].isin([1, 2])]

# Print the result
first_second_class.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
9             10         1       2
11            12         1       1
..           ...       ...     ...
880          881         1       2
883          884         0       2
886          887         0       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
883                      Banfield, Mr. Frederick James    male  28.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked  fare per year
1        0          PC 17599  71.2833   C85        C       1.875876
3        0            113803  53.1000  C123        S       1.517143
6        0             17463  51.8625   E46        S       0.960417
9        0            237736  30.0708   NaN        C       2.147914
11       0            113783  26.5500  C103        S       0.457759
..     ...               ...      ...   ...      ...            ...
880      1            230433  26.0000   NaN        S       1.040000
883      0  C.A./SOTON 34068  10.5000   NaN        S       0.375000
886      0            211536  13.0000   NaN        S       0.481481
887      0            112053  30.0000   B42        S       1.578947
889      0            111369  30.0000  C148        C       1.153846

[400 rows x 13 columns]>

In [12]:
#put  a column 'fare per year' by divide Fare by Age
df["fare per year"] = df["Fare"] / df["Age"]

# Print the result
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000

In [16]:
# add rows where 'fare per year' is higher than 5
high_fare_age = df[df["fare per year"] > 5]

# Print the result
high_fare_age.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,10.537500
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,14.562500
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,13.859733
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S,5.669643

In [15]:
# Sort 'high fare age' by 'fare per year' in descending order
high_fare_age_srt = high_fare_age.sort_values(by="fare per year", ascending=False)

# Display the sorted result
high_fare_age_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,164.728261
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,75.775000
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,46.900000
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,39.687500
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,39.000000

In [24]:
# put 'Name' and 'fare per year' columns from 'high fare age srt'
result = high_fare_age_srt[["Name", "fare per year"]]

# show the first 5 rows of the result
result.head()

                                Name  fare per year
305   Allison, Master. Hudson Trevor     164.728261
297     Allison, Miss. Helen Loraine      75.775000
386  Goodwin, Master. Sidney Leonard      46.900000
164     Panula, Master. Eino Viljami      39.687500
183        Becker, Master. Richard F      39.000000

In [25]:
# Put a column 'fare per class' and divide Fare by Pclass
df["fare per class"] = df["Fare"] / df["Pclass"]

# Show the first 5 rows to check the result
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year,fare per class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876,71.283300
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808,2.641667
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143,53.100000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333

In [26]:
# Add rows where the passenger is male and an adult
adult_males = df[(df["Sex"] == "male") & (df["Age"] >= 18)]

# Show  the first 5 rows to check the result
adult_males.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year,fare per class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0.960417,51.862500
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,0.402500,2.683333
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,0.801923,10.425000

In [27]:
# Sort 'adult males' by 'fare per class' in descending order
adult_males_srt = adult_males.sort_values(by="fare per class", ascending=False)

# show  the first 5 rows to check the result
adult_males_srt.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year,fare per class
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,14.637977,512.3292
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,14.231367,512.3292
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,13.842105,263.0000
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,4.109375,263.0000
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,10.313367,247.5208

In [28]:
# Choose  'Name', 'Age', and 'fare per class' columns from 'adult males srt'
result = adult_males_srt[["Name", "Age", "fare per class"]]

# Show  the first 5 rows to check the result
result.head()

                                   Name   Age  fare per class
737              Lesurer, Mr. Gustave J  35.0        512.3292
679  Cardeza, Mr. Thomas Drake Martinez  36.0        512.3292
27       Fortune, Mr. Charles Alexander  19.0        263.0000
438                   Fortune, Mr. Mark  64.0        263.0000
118            Baxter, Mr. Quigg Edmond  24.0        247.5208

In [29]:
# Show  total Fare paid by all passengers
total_fare = df["Fare"].sum()

# Show the result
total_fare

28693.9493

In [32]:
# Put passengers in first class (Pclass is 1)
first_class_passengers = df[df["Pclass"] == 1]

# Show the total Fare paid by first class passengers
total_fare_first_class = first_class_passengers["Fare"].sum()

# printing the result
total_fare_first_class

18177.4125

In [33]:
# Show passengers riding in second class (Pclass is 2)
second_class_passengers = df[df["Pclass"] == 2]

# Calculate  total fare paid by the second-class travelers
total_fare_second_class = second_class_passengers["Fare"].sum()

# Show the result for second class
total_fare_second_class

# EXTRACT the passengers riding in third class (Pclass is 3)
third_class_passengers = df[df["Pclass"] == 3]

# Calculate the total fare paid by the third-class travelers
total_fare_third_class = third_class_passengers["Fare"].sum()

# Printing the result for third class
total_fare_third_class

6714.6951

In [34]:
# Calculate the total fare for first, second, and third class passengers
total_fare_first_class = df[df["Pclass"] == 1]["Fare"].sum()
total_fare_second_class = df[df["Pclass"] == 2]["Fare"].sum()
total_fare_third_class = df[df["Pclass"] == 3]["Fare"].sum()

# Mix the totals into a list
fare_totals = [total_fare_first_class, total_fare_second_class, total_fare_third_class]

# Printing the fare totals list
fare_totals

[18177.4125, 3801.8417, 6714.6951]

In [35]:
# Total fare for all passengers
total_fare = df["Fare"].sum()

# Calculate the proportion of fare revenue for each class
proportion_first_class = total_fare_first_class / total_fare
proportion_second_class = total_fare_second_class / total_fare
proportion_third_class = total_fare_third_class / total_fare

# Mixing the proportions into a list
proportions = [proportion_first_class, proportion_second_class, proportion_third_class]

# Print the proportions list
proportions

[0.6334928771899656, 0.1324962855496507, 0.23401083726038366]

In [36]:
# Show a new column 'age group' to categorize passengers based on age
df["age group"] = pd.cut(df["Age"], bins=[0, 17, 64, float('inf')], labels=["child", "adult", "senior"])

# Displpay the first 5 rows to check the result
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,fare per year,fare per class,age group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.329545,2.416667,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1.875876,71.283300,adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.304808,2.641667,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1.517143,53.100000,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.230000,2.683333,adult

In [37]:
# Calculate the total number of passengers on the Titanic
total_passengers = len(df)

# Show the result
total_passengers

891

In [38]:
# Count the number of passengers in each age group
age_group_count = df["age group"].value_counts()

# Show the result
age_group_count

age group
adult     590
child     113
senior     11
Name: count, dtype: int64

In [40]:
# Calculate proportion of passengers in every  age group
age_group_proportion = age_group_count / total_passengers

# Show  the result
age_group_proportion

age group
adult     0.662177
child     0.126824
senior    0.012346
Name: count, dtype: float64